### ISSUE TITLE
Error message produced on Mac

### ISSUE THREAD

**Issue by gusberinger** [pipeseroni/pipes.sh#27]
This is on Mac OS X El Capitan installed via homebrew

![Terminal Window](http://i.imgur.com/T0as8tl.png)

The program itself works fine I just want to now how to silence the error message. It is also particularly bad when running tmux.

**Comment by maclockard** [comment]
I'm getting the same issue here.

**Comment by patillacode** [comment]
+1

Plus I cannot access the script unless I specifically call it with the absolute path 
`/usr/local/Cellar/pipes-sh/1.1.0/bin/pipes.sh` when installing with `brew`

**Comment by Foggalong** [comment]
Should now be fixed in 1.2.0 :)

**Comment by patillacode** [comment]
Cheers!

**Comment by Sam1066** [comment]
I installed with brew last night and I'm getting this error still :(
